### PR TITLE
fix no focus causing failed rendering

### LINKED ISSUE #82: Starting without a focused input holds a stuck cursor on all placeholders

### PR DESCRIPTION
**Pull request by bytemunch**
fixes #82

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -507,12 +507,17 @@ fn cosmic_editor_builder(
...
             &mut font_system.0,
             Metrics::new(metrics.font_size, metrics.line_height).scale(metrics.scale_factor),
         );
         // buffer.set_wrap(&mut font_system.0, cosmic_text::Wrap::None);
-        let editor = Editor::new(buffer);
+        buffer.set_redraw(true);
+        let mut editor = Editor::new(buffer);
+
+        let mut cursor = editor.cursor();
+        cursor.color = Some(cosmic_text::Color::rgba(0, 0, 0, 0));
```
Comment (Dimchikkk) [inline src/lib.rs:519]: why do we need to set cursor color? :) 
(just want to understand the code)

Comment (bytemunch) [reply src/lib.rs:519]: Fixes a bug that appeared, initial render had a cursor on every widget, having an invisible cursor initially fixed it. When focused the cursor blink routine takes over and makes it visible again

**Review by Dimchikkk — APPROVED** [review]
