### PR TITLE
fix cursor blink on editors with transparency

### LINKED ISSUE #16: editors with alpha do not hide cursor correctly
when the BackgroundColor has an alpha value, the cursor does not pick the value up when it should be hidden
ctbug

### PR DESCRIPTION
**Pull request by bytemunch**
fixes #16 

also should make blinking cursor work for editors with images as background, untested so far

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1207,7 +1204,7 @@ fn blink_cursor(
             let new_color = if *visible {
                 None
             } else {
-                Some(bevy_color_to_cosmic(bg_color.0))
+                Some(cosmic_text::Color::rgba(0, 0, 0, 0))
```
Comment (Dimchikkk) [inline src/lib.rs:1207]: Interesting :)

**Review by Dimchikkk — APPROVED** [review]
